<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>agda</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~A</string>
	<key>name</key>
	<string>Agda</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\b(module)\s+([^\(\)\{\}[:space:]=→λ∀?][^\(\)\{\}[:space:]]*)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.agda</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.module.agda</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\bwhere\b|=)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.agda</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.declaration.module.agda</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#module_param</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#module_params</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#module_params_implicit</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(import|open(\s+import)?)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.agda</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.import.agda</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(as|using|renaming|hiding|public)\b</string>
					<key>name</key>
					<string>keyword.other.agda</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(record)\s+([^\(\)\{\}[:space:]=→λ∀?][^\(\)\{\}[:space:]]*)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.agda</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.record.agda</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\b(where)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.agda</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.declaration.record.agda</string>
			<key>patterns</key>
			<array/>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(data)\s+([^\(\)\{\}[:space:]=→λ∀?][^\(\)\{\}[:space:]]*)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.agda</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.data.agda</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\b(where)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.agda</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.declaration.record.agda</string>
			<key>patterns</key>
			<array/>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.agda</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.agda</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\binfix[lr]\b</string>
			<key>name</key>
			<string>keyword.operator.agda</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(where|as|case|field|constructor|record|private|public|abstract|mutual)\b</string>
			<key>name</key>
			<string>keyword.other.agda</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\s)[=→λ∀?]</string>
			<key>name</key>
			<string>keyword.operator.agda</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.agda</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.colon.agda</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*([^\(\)\{\}[:space:]=→λ∀?][^\(\)\{\}[:space:]]*)\s*(:)(?=\s|$)</string>
			<key>name</key>
			<string>meta.function.type-declaration.agda</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.agda</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.agda</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.agda</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(NUL|SOH|STX|ETX|EOT|ENQ|ACK|BEL|BS|HT|LF|VT|FF|CR|SO|SI|DLE|DC1|DC2|DC3|DC4|NAK|SYN|ETB|CAN|EM|SUB|ESC|FS|GS|RS|US|SP|DEL|[abfnrtv\\\"'\&amp;])</string>
					<key>name</key>
					<string>constant.character.escape.agda</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\o[0-7]+|\\x[0-9A-Fa-f]+|\\[0-9]+</string>
					<key>name</key>
					<string>constant.character.escape.octal.agda</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\^[A-Z@\[\]\\\^_]</string>
					<key>name</key>
					<string>constant.character.escape.control.agda</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([0-9]+|0([xX][0-9a-fA-F]+))\b</string>
			<key>name</key>
			<string>constant.numeric.agda</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#dashComment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#pragma</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#blockComment</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>blockComment</key>
		<dict>
			<key>begin</key>
			<string>{-</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.agda</string>
				</dict>
			</dict>
			<key>end</key>
			<string>-}</string>
			<key>name</key>
			<string>comment.block.agda</string>
		</dict>
		<key>dashComment</key>
		<dict>
			<key>begin</key>
			<string>(--) </string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.agda</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.double-dash.agda</string>
		</dict>
		<key>identifier</key>
		<dict>
			<key>comment</key>
			<string>not so much here to be used as to be a reference</string>
			<key>match</key>
			<string>\b[^\(\)\{\}[:space:]=→λ∀?][^\(\)\{\}[:space:]]*</string>
			<key>name</key>
			<string>entity.name.function.agda</string>
		</dict>
		<key>module_param</key>
		<dict>
			<key>match</key>
			<string>\b[^\(\)\{\}[:space:]=→λ∀?][^\(\)\{\}[:space:]]*</string>
			<key>name</key>
			<string>entity.name.parameter.agda</string>
		</dict>
		<key>module_params</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.declaration.module.params.agda</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#module_param</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type_sig_rhs</string>
				</dict>
			</array>
		</dict>
		<key>module_params_implicit</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>meta.declaration.module.params.agda</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#module_param</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type_sig_rhs</string>
				</dict>
			</array>
		</dict>
		<key>pragma</key>
		<dict>
			<key>applyEndPatternLast</key>
			<integer>1</integer>
			<key>begin</key>
			<string>\{-#</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.pragma.agda</string>
				</dict>
			</dict>
			<key>end</key>
			<string>#-\}</string>
			<key>name</key>
			<string>support.pragma.block.agda</string>
		</dict>
		<key>type_sig_rhs</key>
		<dict>
			<key>begin</key>
			<string>:</string>
			<key>end</key>
			<string>(?=[\)\}])</string>
			<key>name</key>
			<string>meta.declaration.module.params.typesig.agda</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b[^\(\)\{\}[:space:]=→λ∀?][^\(\)\{\}[:space:]]*</string>
					<key>name</key>
					<string>storage.type.agda</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.agda</string>
	<key>uuid</key>
	<string>F9829CA7-1CEB-4A7E-AD45-0C1622729B8A</string>
</dict>
</plist>
